name: Ушу в Екатеринбурге
encoding: utf-8
markdown: redcarpet
pygments: false
permalink: /xinwen/:year/:month/:day/:title/
paginate: 4
paginate_path: /xinwen/page:num

exclude:
  - CNAME
  - README.md
  - run.bat
  - orig

redcarpet:
  extensions:
    - tables
    - autolink

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
